[build]
  command = "npm run build"
  publish = "-skill-surge-ui/dist"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 