
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnrvcmeysdwpldisjzxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJucnZjbWV5c2R3cGxkaXNqenh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzE5ODksImV4cCI6MjA2NDAwNzk4OX0.kqmVKwO4HE86EVf3WPctfYxnhqasyfuxMopVVCBtgqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
